---
- name: Install Uchiwa - Opensource Dashboard for Sensu monitoring 
  yum:
    name: uchiwa
    state: present

- name: Start Uchiwa
  service: 
    name: uchiwa
    state: started
    enabled: yes

- name: Install Nginx 
  yum:
    name: nginx
    state: present

- name: Configure Nginx to forward request to Uchiwa
  copy:
    src: "{{ playbook_dir }}/../roles/internal/uchiwa/files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"

- name: Configure Nginx to forward request to Uchiwa 
  copy:
    src: "{{ playbook_dir }}/../roles/internal/uchiwa/files/uchiwa.conf" 
    dest: "/etc/nginx/conf.d/uchiwa.conf"

- name: Just add Sensu host server to Uchiwa dashboard. You need to change this later
  template:
    src: "uchiwa.json"
    dest: "/etc/sensu/uchiwa.json"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

# tasks file for sake-of-restart
- name: Wait for 10 seconds to restart Uchiwa
  command: sleep 10s

- name: Restart Uchiwa
  service:
    name: uchiwa
    state: restarted
    enabled: yes
