---
# tasks file for windows-service

 - name: Download the sensu package 
   win_get_url:
      url: 'https://sensu.global.ssl.fastly.net/msi/sensu-0.26.0-1.msi'
      dest: 'C:\Users\Administrator\Downloads\sensu-0.26.0-1.msi'

 - name: Install sensu package
   win_msi:
      path : 'C:\Users\Administrator\Downloads\sensu-0.26.0-1.msi'
      wait : true
 
 - name: Create conf.d directory
   win_file: path=C:\opt\sensu\conf.d state=directory

 - name: Add the service scripts
   win_copy: src={{ item.src }} dest={{ item.dest }} 
   with_items:
     - {src: "{{ playbook_dir }}/../roles/internal/windows-service/files/client.json", dest: "C:/opt/sensu/conf.d/client.json"}
     - {src: "{{ playbook_dir }}/../roles/internal/windows-service/files/redis.json", dest: "C:/opt/sensu/conf.d/redis.json"}
     - {src: "{{ playbook_dir }}/../roles/internal/windows-service/files/transport.json", dest: "C:/opt/sensu/conf.d/transport.json"}
     - {src: "{{ playbook_dir }}/../roles/internal/windows-service/files/sensu-client.xml", dest: "C:/opt/sensu/bin/sensu-client.xml"}
                          
# - name: Create sensu-cllient service
#   raw: sc.exe \\172.31.25.143 create sensu-client start= delayed-auto binPath= c:\opt\sensu\bin\sensu-client.exe DisplayName= "Sensu Client"
#   raw: sc.exe \\172.31.21.185 create sensu-client start= delayed-auto binPath= c:\opt\sensu\bin\sensu-client.exe DisplayName= "Sensu Client"
 
 - name: Ensure sensu-client service is started
   win_service: name=sensu-client start_mode=auto state=started
