---
# tasks file for sensu
- name: Add GPG key for InfluxDB
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: present

- name: Add Sensu repository for Ubuntu 16
  template:
    src: influxdb.ubuntu16.list
    dest: /etc/apt/sources.list.d/influxdb.list
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: Add Sensu repository for Ubuntu 14
  template:
    src: influxdb.ubuntu14.list
    dest: /etc/apt/sources.list.d/influxdb.list
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

# add grafana repo
- name: add grafana repo
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
    state: present

# add grafana key
- name: Add GPG key for grafana
  apt_key:
    url: "https://packagecloud.io/gpg.key"
    state: present

- name: Only run "update_cache=yes"
  apt:
    update_cache: yes

- name: Install influxdb
  apt: name={{item}} state=present 
  with_items:
     - influxdb
     - grafana
     - python3-pip

- name: Install influxdb python module
  pip:
    name: influxdb

- name: Configuration
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner=root group=root
  with_items:
   - {src: "handlers.json.j2", dest: "/etc/sensu/conf.d/handlers.json", mode: "0644"}
   - {src: "influxdb.conf.j2", dest: "/etc/influxdb/influxdb.conf", mode: "0644"}
   - {src: "grafana.ini.j2", dest: "/etc/grafana/grafana.ini", mode: "0644"}
   - {src: "influxdb_line_protocol.rb", dest: "/etc/sensu/extensions/influxdb_line_protocol.rb", mode: "0644"}
   - {src: "body.json", dest: "/tmp/body.json", mode: "0644"}

 
- name: Requred gem installation
  command: /opt/sensu/embedded/bin/gem install "{{item}}"
  with_items:
    - influxdb

- name: Start Influxdb service
  service: name={{item}} enabled=yes state=restarted
  with_items:
     - influxdb

#- name: Create database
#  influxdb_database:
#     hostname: "127.0.0.1"
#     database_name: "sensu"
#     state: present

- name: Create database using custom credentials
  influxdb_database:
      hostname: "{{influxdb_ip_address}}"
      username: "{{influxdb_username}}"
      password: "{{influxdb_password}}"
      database_name: "{{influxdb_database_name}}"
      state: present
      

- name: Start Influxdb, Grafana, Sensu-server
  service: name={{item}} enabled=yes state=restarted
  with_items:
     - influxdb
     - grafana-server
     - sensu-server
     
- name: datasource add
  shell: curl -u admin:admin -H "Content-Type:application/json" -d @/tmp/body.json  http://{{ sensu_server_ip }}:3001/api/datasources
  tags:
  - data
      
