---
# tasks file for sensu
- name: Add Sensu repository 
  yum_repository:
    name: sensu
    description: Repository for Sensu 
    baseurl: http://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/ 
    enabled: yes
    gpgcheck: no

- name: Install EPEL packge
  yum:
    name: epel-release
    state: present

- name: Install Sensu-Core server
  yum:
    name: sensu 
    state: present 

- service:
    name: sensu-server
    state: started

- service:
    name: sensu-api
    state: started

- service:
    name: sensu-client
    state: started

#- file:
#    path: /etc/sensu/conf.d
#    state: directory
#    mode: 0755
#
#- name: Copy configuration files in conf.d 
#  template: src={{ item.src }} dest={{ item.dest }}
#  with_items:
#    - { src: "api.json", dest: "/etc/sensu/conf.d/api.json" }
#    - { src: "transport.json", dest: "/etc/sensu/conf.d/transport.json" }
#    - { src: "redis.json", dest: "/etc/sensu/conf.d/redis.json" }
#    - { src: "uchiwa.json", dest: "/etc/sensu/uchiwa.json" }
#
#
#- name: Copy plugins to Sensu
#  copy: src={{ item.src }} dest={{ item.dest }}
#  with_items:
#    - { src: "{{ playbook_dir }}/../roles/internal/sensu/templates/conf.d/", dest: "/etc/sensu/conf.d/" }
#
#- name: Installing Sensu Plugin
#  command: sudo sensu-install -p {{ item }}
#  with_items:
#    - sensu-plugins-disk-checks
#    - sensu-plugins-memory-checks
#    - sensu-plugins-cpu-checks
#    - sensu-plugins-network-checks
#    - sensu-plugins-ntp
#    - sensu-plugins-snmp
#    - sensu-plugins-load-checks
#    - sensu-plugins-mysql
#    - sensu-plugins-filenr
#    - sensu-plugins-influxdb
#    - sensu-plugins-mailer
